services:
  collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - collector

  app:
    build:
      context: ..
      dockerfile: e2e/app/Dockerfile
    environment:
      OTEL_SERVICE_NAME: gunicorn-app
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://collector:4318/v1/metrics
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_GUNICORN_TRACE_WORKERS: "true"
    ports:
      - "8000:8000"
    depends_on:
      - collector

